import { chromium } from 'playwright-core';
const exe = '/Users/mac/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
const browser = await chromium.launch({ executablePath: exe, headless: true, args: ['--disable-blink-features=AutomationControlled','--no-sandbox'] });
const ctx = await browser.newContext({ userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36', locale: 'en-US', viewport: { width: 1440, height: 1000 } });
const page = await ctx.newPage();
await page.goto('https://www.myhome.ge/en/real-estate/?currencyID=1&dealTypeID=1', { waitUntil: 'domcontentloaded', timeout: 45000 });
await page.waitForTimeout(5000);
await page.evaluate(() => { [...document.querySelectorAll('button')].find(x => x.innerText.trim() === 'Accept all')?.click(); });
await page.waitForTimeout(1000);
// open Show Filters (sidebar?)
await page.evaluate(() => { [...document.querySelectorAll('button')].find(x => x.innerText.includes('Show Filters'))?.click(); });
await page.waitForTimeout(2500);
await page.screenshot({ path: 'myhome_sidebar.png' });
const text = await page.evaluate(() => document.body.innerText);
console.log(text.slice(0, 2500));
console.log('=== SORT OPTIONS ===');
await page.evaluate(() => { [...document.querySelectorAll('button')].find(x => x.innerText.includes('Date descending'))?.click(); });
await page.waitForTimeout(1200);
const sortTxt = await page.evaluate(() => document.body.innerText);
const m = sortTxt.match(/Date descending[\s\S]{0,400}/);
console.log(m ? m[0] : 'n/a');
await browser.close();
