/**
 * SIVRCE — committed city shell (OSM neighborhoods + landmarks) per city.
 * Data: src/data/world-city-osm.json (OSM, generated by scripts/fetch-world-city-osm.ts).
 * NEVER import from a client component — multi-MB JSON breaks the device-budget
 * lock. The map page (RSC) is the only consumer: it bakes a ≤220-pin shell for
 * the boot city into Map3D props; everywhere else stays live-Overpass.
 * ponytail: lazy per-city index (flat scan on miss ≈ 0 rows — keyed lookup);
 * per-city chunks only if a profile says so.
 */

import raw from '@/data/world-city-osm.json'
import { allMetroStationsForCity } from '@/lib/countries/world-metro-all'
import { cityBySlug } from '@/lib/map/user-place.server'
import {
  SHELL_HOOD_CAP,
  SHELL_LANDMARK_CAP,
  SHELL_METRO_CAP,
  type CityShell,
  type CityShellHood,
  type CityShellPin,
} from '@/lib/map/city-shell'

type Row = { n: string; la: number; ln: number; k: 'h' | 'l'; c: string }

const ROWS = (raw as { places: Row[] }).places as Row[]

export const CITY_OSM_COUNT: number = (raw as { count: number }).count
export const CITY_OSM_FETCHED_AT: string = (raw as { fetchedAt: string }).fetchedAt

let cityIndex: Map<string, Row[]> | null = null

function index(): Map<string, Row[]> {
  if (!cityIndex) {
    cityIndex = new Map()
    for (const r of ROWS) {
      const list = cityIndex.get(r.c)
      if (list) list.push(r)
      else cityIndex.set(r.c, [r])
    }
  }
  return cityIndex
}

/** Committed shell rows for a city slug (empty = live Overpass covers it). */
export function cityShellPlaces(
  citySlug: string,
): { hoods: CityShellHood[]; pins: CityShellPin[] } {
  const rows = index().get(citySlug)
  if (!rows) return { hoods: [], pins: [] }
  const hoods: CityShellHood[] = []
  const pins: CityShellPin[] = []
  for (const r of rows) {
    if (r.k === 'h') {
      if (hoods.length < SHELL_HOOD_CAP) hoods.push({ n: r.n, la: r.la, ln: r.ln })
    } else if (pins.length < SHELL_LANDMARK_CAP) {
      pins.push({ n: r.n, la: r.la, ln: r.ln, k: 'landmark' })
    }
  }
  return { hoods, pins }
}

/** Slugs with committed shell rows (check + tooling). */
export function cityShellSlugs(): string[] {
  return [...index().keys()]
}

/**
 * Boot-city shell for /map — hoods + landmarks (committed OSM) + metro
 * stations (world-metro-all). Null when the boot point isn't near a listed
 * city: the live Overpass overlay stays the only layer there.
 */
export function cityShellFor(slug: string): CityShell | null {
  const city = cityBySlug(slug)
  if (!city) return null
  const { hoods, pins } = cityShellPlaces(slug)
  for (const s of allMetroStationsForCity(slug)) {
    if (pins.length >= SHELL_LANDMARK_CAP + SHELL_METRO_CAP) break
    pins.push({ n: s.name, la: s.lat, ln: s.lng, k: 'metro' })
  }
  if (hoods.length === 0 && pins.length === 0) return null
  return { slug: city.slug, en: city.en, ka: city.ka, cc: city.cc, hoods, pins }
}
