/**
 * SIVRCE — every metro/subway station on earth (server-only).
 * Data: src/data/world-metro-all.json (OSM `station=subway`, generated by
 * scripts/fetch-world-metro-osm.ts). NEVER import from a client component —
 * 1.3 MB JSON in the browser breaks the device-budget lock. PlaceContext
 * (RSC) is the only UI consumer: Tbilisi walking grid first, this everywhere
 * else, committed hub lines (data/world-metros) enriching interchanges.
 * ponytail: flat scan (~18k haversine ≈ 1 ms) + lazy city index; per-city
 * chunks or spatial index only if a profile says so.
 */

import { createHash } from 'node:crypto'
import raw from '@/data/world-metro-all.json'
import { WORLD_METROS } from '@/data/world-metros'
import { METRO_MAX_CATCHMENT_M, METRO_NEAR_M } from '@/lib/geo/nearest-poi-constants'

export interface AllMetroStation {
  name: string
  line: string
  citySlug: string
  lat: number
  lng: number
}

export interface AllNearMetro {
  name: string
  /** Curated hub lines at interchanges, else OSM route_ref, else ''. */
  line: string
  system: string
  citySlug: string
  cc: string
  meters: number
  walkMin: number
  /** 'near' ≤800 m (~10 min) · 'walk' ≤2500 m catchment — same zones as Tbilisi. */
  zone: 'near' | 'walk'
}

type Row = { n: string; la: number; ln: number; l: string; c: string }

const ROWS = (raw as { stations: Row[] }).stations

export const ALL_METRO_COUNT: number = (raw as { count: number }).count
export const ALL_METRO_FETCHED_AT: string = (raw as { fetchedAt: string }).fetchedAt

let cityIndex: Map<string, AllMetroStation[]> | null = null

function index(): Map<string, AllMetroStation[]> {
  if (!cityIndex) {
    cityIndex = new Map()
    for (const r of ROWS) {
      const s: AllMetroStation = { name: r.n, line: r.l, citySlug: r.c, lat: r.la, lng: r.ln }
      const list = cityIndex.get(r.c)
      if (list) list.push(s)
      else cityIndex.set(r.c, [s])
    }
  }
  return cityIndex
}

/** Every committed station pin for a map-city slug ([] = live lookup, not "no metro"). */
export function allMetroStationsForCity(citySlug: string): AllMetroStation[] {
  return index().get(citySlug) ?? []
}

/** Flat committed interchange pins for line/system enrichment. */
const HUBS = WORLD_METROS.flatMap((m) =>
  m.stations.map((s) => ({ name: s.name, line: s.line, system: m.name, cc: s.cc, lat: s.lat, lng: s.lng })),
)

function haversineM(aLat: number, aLng: number, bLat: number, bLng: number): number {
  const R = 6_371_000
  const toR = Math.PI / 180
  const dLat = (bLat - aLat) * toR
  const dLng = (bLng - aLng) * toR
  const a =
    Math.sin(dLat / 2) ** 2 + Math.cos(aLat * toR) * Math.cos(bLat * toR) * Math.sin(dLng / 2) ** 2
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(a)))
}

/** Meters to the nearest world pin; far listings get the same sentinel as pois.metroMeters. */
export function worldMetroMeters(lat: number, lng: number): number {
  const n = nearestAllMetroStation(lat, lng)
  return n ? n.meters : 999_999
}

export interface MetroChip {
  n: string
  m: number
  w: number
}

/** Compact card/search payload ({n,m,w} keeps JSON small); null outside catchment. */
export function worldMetroChip(lat: number, lng: number): MetroChip | null {
  const n = nearestAllMetroStation(lat, lng)
  return n ? { n: n.name, m: n.meters, w: n.walkMin } : null
}

export interface WorldMetroSeedRow {
  id: string
  name: string
  lng: number
  lat: number
  meta: string
}

// ponytail: same sha256→UUID layout as poiUuid, inline so this module never
// touches @/lib/map/pois (1.1 MB client JSON) or the DB layer.
function seedUuid(key: string): string {
  const h = createHash('sha256').update(`sivrce-poi:${key}`).digest()
  const b = Buffer.from(h.subarray(0, 16))
  b[6] = (b[6]! & 0x0f) | 0x40
  b[8] = (b[8]! & 0x3f) | 0x80
  const hex = b.toString('hex')
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`
}

/** Pure seed rows for the pois-table world insert (DB-free; stable ids survive renames). */
export function worldMetroSeedRows(): WorldMetroSeedRow[] {
  return ROWS.map((s) => ({
    id: seedUuid(`world-metro:${s.la.toFixed(6)},${s.ln.toFixed(6)}`),
    name: s.n.slice(0, 240),
    lng: s.ln,
    lat: s.la,
    meta: JSON.stringify({ source: 'osm-world', city: s.c, line: s.l }),
  }))
}
/**
 * Nearest of all 18k+ world stations within catchment.
 * Null = outside catchment, never "no metro": live OSM/Nominatim resolves the rest.
 */
export function nearestAllMetroStation(lat: number, lng: number): AllNearMetro | null {
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null
  let best: Row | null = null
  let bestM = Infinity
  for (const r of ROWS) {
    const m = haversineM(lat, lng, r.la, r.ln)
    if (m < bestM) {
      bestM = m
      best = r
    }
  }
  if (!best || bestM > METRO_MAX_CATCHMENT_M) return null
  const meters = Math.round(bestM)
  let line = best.l
  let system = ''
  let cc = ''
  let hubM = 250
  for (const h of HUBS) {
    const m = haversineM(lat, lng, h.lat, h.lng)
    if (m <= hubM) {
      hubM = m
      line = h.line
      system = h.system
      cc = h.cc
    }
  }
  return {
    name: best.n,
    line,
    system,
    citySlug: best.c,
    cc,
    meters,
    walkMin: Math.max(1, Math.round(meters / 80)),
    zone: meters <= METRO_NEAR_M ? 'near' : 'walk',
  }
}
