import assert from 'node:assert/strict'
import { canonicalizeDistrict, districtSearchValues } from './district-canon'

assert.equal(canonicalizeDistrict('Saburtalo'), 'საბურთალო')
assert.equal(canonicalizeDistrict('Vake'), 'ვაკე')
assert.equal(canonicalizeDistrict('ვაკე-საბურთალო'), 'საბურთალო')
assert.equal(canonicalizeDistrict('საბურთალო, თბილისი'), 'საბურთალო')
assert.equal(canonicalizeDistrict('ლისის ტბა'), 'ლისი')
assert.equal(canonicalizeDistrict('Airport (district)', 'ბათუმი'), 'აეროპორტის უბანი')
assert.equal(canonicalizeDistrict('ძველი ბათუმი', 'ბათუმი'), 'ძველი ბათუმის უბანი')
assert.equal(canonicalizeDistrict('ძველი ქალაქი', 'ბათუმი'), 'ძველი ბათუმის უბანი')
assert.equal(canonicalizeDistrict('გიორგიწმინდა', 'თბილისი'), 'გიორგიწმინდას დასახლება')
assert.equal(canonicalizeDistrict('Chugureti'), 'ჩუღურეთი')
assert.ok(districtSearchValues('ვაკე-საბურთალო').includes('ვაკე'))
assert.ok(!districtSearchValues('საბურთალო', 'თბილისი').includes('ლისი'))
assert.ok(!districtSearchValues('ვაკე', 'თბილისი').includes('ბაგები'))
assert.ok(!districtSearchValues('ვაკე', 'თბილისი').includes('დიღომი'))
assert.equal(canonicalizeDistrict('აეროპორტის რაიონი, ადლიას ქ. 53', 'ბათუმი'), 'აეროპორტის უბანი')
assert.equal(canonicalizeDistrict('ჩაკვი, შავი ზღვის სანაპირო'), '')
assert.equal(canonicalizeDistrict('ვაკის რაიონი'), 'ვაკე')
assert.equal(canonicalizeDistrict('Tskhvarichamia'), 'ცხვარიჭამია')
assert.ok(districtSearchValues('ვაკე,საბურთალო', 'თბილისი').includes('საბურთალო'))
assert.ok(!districtSearchValues('ვაკე,საბურთალო', 'თბილისი').includes('ვეძისი'))

console.log('district-canon: ok')
