/* GENERATED by scripts/gen-footer-cols.ts — do not edit; npm run prebuild refreshes.
 * Snapshot of seo-pages.footerKeywordCols() so the client Footer never imports the
 * seo-pages → data/listings graph. */
import type { FooterCol } from './seo-pages'

export const FOOTER_COLS: FooterCol[] = [
  {
    "id": "sale",
    "title": {
      "ka": "იყიდება",
      "en": "For sale",
      "ru": "Продажа"
    },
    "links": [
      {
        "href": "/sale/apartments-1",
        "label": {
          "ka": "1-ოთახიანი ბინები იყიდება",
          "en": "1-Room Apartments for sale",
          "ru": "Продажа 1-комнатных квартир"
        }
      },
      {
        "href": "/sale/apartments-2",
        "label": {
          "ka": "2-ოთახიანი ბინები იყიდება",
          "en": "2-Room Apartments for sale",
          "ru": "Продажа 2-комнатных квартир"
        }
      },
      {
        "href": "/sale/apartments-3",
        "label": {
          "ka": "3-ოთახიანი ბინები იყიდება",
          "en": "3-Room Apartments for sale",
          "ru": "Продажа 3-комнатных квартир"
        }
      },
      {
        "href": "/sale/apartments-4",
        "label": {
          "ka": "4+ ოთახიანი ბინები იყიდება",
          "en": "4+ Room Apartments for sale",
          "ru": "Продажа квартир с 4+ комнатами"
        }
      },
      {
        "href": "/sale/houses",
        "label": {
          "ka": "სახლები და აგარაკები იყიდება",
          "en": "Houses & Cottages for sale",
          "ru": "Продажа домов и дач"
        }
      },
      {
        "href": "/sale/land",
        "label": {
          "ka": "მიწის ნაკვეთები იყიდება",
          "en": "Land Plots for sale",
          "ru": "Продажа земельных участков"
        }
      },
      {
        "href": "/sale/commercial",
        "label": {
          "ka": "კომერციული ფართები იყიდება",
          "en": "Commercial Property for sale",
          "ru": "Продажа коммерческой недвижимости"
        }
      },
      {
        "href": "/sale/apartments/tbilisi",
        "label": {
          "ka": "ბინები იყიდება თბილისში",
          "en": "Apartments for sale in Tbilisi",
          "ru": "Продажа квартир в Тбилиси"
        }
      }
    ]
  },
  {
    "id": "rent",
    "title": {
      "ka": "ქირავდება",
      "en": "For rent",
      "ru": "Аренда"
    },
    "links": [
      {
        "href": "/rent/apartments-1",
        "label": {
          "ka": "1-ოთახიანი ბინები ქირავდება",
          "en": "1-Room Apartments for rent",
          "ru": "Аренда 1-комнатных квартир"
        }
      },
      {
        "href": "/rent/apartments-2",
        "label": {
          "ka": "2-ოთახიანი ბინები ქირავდება",
          "en": "2-Room Apartments for rent",
          "ru": "Аренда 2-комнатных квартир"
        }
      },
      {
        "href": "/rent/apartments-3",
        "label": {
          "ka": "3-ოთახიანი ბინები ქირავდება",
          "en": "3-Room Apartments for rent",
          "ru": "Аренда 3-комнатных квартир"
        }
      },
      {
        "href": "/rent/houses",
        "label": {
          "ka": "სახლები და აგარაკები ქირავდება",
          "en": "Houses & Cottages for rent",
          "ru": "Аренда домов и дач"
        }
      },
      {
        "href": "/rent/commercial",
        "label": {
          "ka": "კომერციული ფართები ქირავდება",
          "en": "Commercial Property for rent",
          "ru": "Аренда коммерческой недвижимости"
        }
      },
      {
        "href": "/lease",
        "label": {
          "ka": "მიწის ნაკვეთები გაიცემა იჯარით",
          "en": "Land Plots for lease",
          "ru": "Аренда земельных участков"
        }
      },
      {
        "href": "/rent/apartments/tbilisi",
        "label": {
          "ka": "ბინები ქირავდება თბილისში",
          "en": "Apartments for rent in Tbilisi",
          "ru": "Аренда квартир в Тбилиси"
        }
      },
      {
        "href": "/rent/apartments/batumi",
        "label": {
          "ka": "ბინები ქირავდება ბათუმში",
          "en": "Apartments for rent in Batumi",
          "ru": "Аренда квартир в Батуми"
        }
      },
      {
        "href": "/rent/apartments/kutaisi",
        "label": {
          "ka": "ბინები ქირავდება ქუთაისში",
          "en": "Apartments for rent in Kutaisi",
          "ru": "Аренда квартир в Кутаиси"
        }
      }
    ]
  },
  {
    "id": "daily",
    "title": {
      "ka": "დღიურად",
      "en": "Daily rent",
      "ru": "Посуточно"
    },
    "links": [
      {
        "href": "/daily/apartments-1",
        "label": {
          "ka": "1-ოთახიანი ბინები დღიურად",
          "en": "1-Room Apartments for daily rent",
          "ru": "1-комнатные квартиры посуточно"
        }
      },
      {
        "href": "/daily/apartments-2",
        "label": {
          "ka": "2-ოთახიანი ბინები დღიურად",
          "en": "2-Room Apartments for daily rent",
          "ru": "2-комнатные квартиры посуточно"
        }
      },
      {
        "href": "/daily/apartments",
        "label": {
          "ka": "ბინები დღიურად",
          "en": "Apartments for daily rent",
          "ru": "Квартиры посуточно"
        }
      },
      {
        "href": "/daily/houses",
        "label": {
          "ka": "სახლები და აგარაკები დღიურად",
          "en": "Houses & Cottages for daily rent",
          "ru": "Дома и дачи посуточно"
        }
      },
      {
        "href": "/daily/apartments/tbilisi",
        "label": {
          "ka": "ბინები დღიურად თბილისში",
          "en": "Apartments for daily rent in Tbilisi",
          "ru": "Квартиры посуточно в Тбилиси"
        }
      },
      {
        "href": "/daily/apartments/batumi",
        "label": {
          "ka": "ბინები დღიურად ბათუმში",
          "en": "Apartments for daily rent in Batumi",
          "ru": "Квартиры посуточно в Батуми"
        }
      },
      {
        "href": "/daily/apartments/tbilisi/saburtalo",
        "label": {
          "ka": "ბინები დღიურად საბურთალოზე",
          "en": "Apartments for daily rent in Saburtalo",
          "ru": "Квартиры посуточно в Сабуртало"
        }
      },
      {
        "href": "/daily/apartments/tbilisi/vake",
        "label": {
          "ka": "ბინები დღიურად ვაკეში",
          "en": "Apartments for daily rent in Vake",
          "ru": "Квартиры посуточно в Ваке"
        }
      }
    ]
  },
  {
    "id": "sale-tbilisi",
    "title": {
      "ka": "ბინები იყიდება თბილისში",
      "en": "Apartments for sale in Tbilisi",
      "ru": "Квартиры на продажу в Тбилиси"
    },
    "links": [
      {
        "href": "/sale/apartments/tbilisi",
        "label": {
          "ka": "თბილისი",
          "en": "Tbilisi",
          "ru": "Тбилиси"
        }
      },
      {
        "href": "/sale/apartments/tbilisi/vake",
        "label": {
          "ka": "ვაკე",
          "en": "Vake",
          "ru": "Ваке"
        }
      },
      {
        "href": "/sale/apartments/tbilisi/saburtalo",
        "label": {
          "ka": "საბურთალო",
          "en": "Saburtalo",
          "ru": "Сабуртало"
        }
      },
      {
        "href": "/sale/apartments/tbilisi/mtatsminda",
        "label": {
          "ka": "მთაწმინდა",
          "en": "Mtatsminda",
          "ru": "Мтацминда"
        }
      },
      {
        "href": "/sale/apartments/tbilisi/didi-dighomi",
        "label": {
          "ka": "დიდი დიღომი",
          "en": "Didi Dighomi",
          "ru": "Диди Дигоми"
        }
      },
      {
        "href": "/sale/apartments/tbilisi/ortachala",
        "label": {
          "ka": "ორთაჭალა",
          "en": "Ortachala",
          "ru": "Ортачала"
        }
      },
      {
        "href": "/sale/apartments/tbilisi/isani",
        "label": {
          "ka": "ისანი",
          "en": "Isani",
          "ru": "Исани"
        }
      },
      {
        "href": "/sale/apartments/tbilisi/gldani",
        "label": {
          "ka": "გლდანი",
          "en": "Gldani",
          "ru": "Глдани"
        }
      }
    ]
  },
  {
    "id": "rent-tbilisi",
    "title": {
      "ka": "ბინები ქირავდება თბილისში",
      "en": "Apartments for rent in Tbilisi",
      "ru": "Квартиры в аренду в Тбилиси"
    },
    "links": [
      {
        "href": "/rent/apartments/tbilisi",
        "label": {
          "ka": "თბილისი",
          "en": "Tbilisi",
          "ru": "Тбилиси"
        }
      },
      {
        "href": "/rent/apartments/tbilisi/vake",
        "label": {
          "ka": "ვაკე",
          "en": "Vake",
          "ru": "Ваке"
        }
      },
      {
        "href": "/rent/apartments/tbilisi/saburtalo",
        "label": {
          "ka": "საბურთალო",
          "en": "Saburtalo",
          "ru": "Сабуртало"
        }
      },
      {
        "href": "/rent/apartments/tbilisi/ortachala",
        "label": {
          "ka": "ორთაჭალა",
          "en": "Ortachala",
          "ru": "Ортачала"
        }
      },
      {
        "href": "/rent/apartments/tbilisi/isani",
        "label": {
          "ka": "ისანი",
          "en": "Isani",
          "ru": "Исани"
        }
      },
      {
        "href": "/rent/apartments/tbilisi/gldani",
        "label": {
          "ka": "გლდანი",
          "en": "Gldani",
          "ru": "Глдани"
        }
      },
      {
        "href": "/rent/apartments-1/tbilisi",
        "label": {
          "ka": "1-ოთახიანი ბინები ქირავდება თბილისში",
          "en": "1-Room Apartments for rent in Tbilisi",
          "ru": "Аренда 1-комнатных квартир в Тбилиси"
        }
      },
      {
        "href": "/rent/apartments-2/tbilisi",
        "label": {
          "ka": "2-ოთახიანი ბინები ქირავდება თბილისში",
          "en": "2-Room Apartments for rent in Tbilisi",
          "ru": "Аренда 2-комнатных квартир в Тбилиси"
        }
      }
    ]
  },
  {
    "id": "popular",
    "title": {
      "ka": "პოპულარული ძებნები",
      "en": "Popular searches",
      "ru": "Популярные запросы"
    },
    "links": [
      {
        "href": "/pledge/apartments",
        "label": {
          "ka": "ბინები გირავდება",
          "en": "Apartments for pledge",
          "ru": "Квартиры под залог"
        }
      },
      {
        "href": "/rent/houses/tbilisi",
        "label": {
          "ka": "სახლები და აგარაკები ქირავდება თბილისში",
          "en": "Houses & Cottages for rent in Tbilisi",
          "ru": "Аренда домов и дач в Тбилиси"
        }
      },
      {
        "href": "/sale/houses/tbilisi",
        "label": {
          "ka": "სახლები და აგარაკები იყიდება თბილისში",
          "en": "Houses & Cottages for sale in Tbilisi",
          "ru": "Продажа домов и дач в Тбилиси"
        }
      },
      {
        "href": "/sale/houses/batumi",
        "label": {
          "ka": "სახლები და აგარაკები იყიდება ბათუმში",
          "en": "Houses & Cottages for sale in Batumi",
          "ru": "Продажа домов и дач в Батуми"
        }
      },
      {
        "href": "/rent/commercial/tbilisi",
        "label": {
          "ka": "კომერციული ფართები ქირავდება თბილისში",
          "en": "Commercial Property for rent in Tbilisi",
          "ru": "Аренда коммерческой недвижимости в Тбилиси"
        }
      },
      {
        "href": "/sale/commercial/tbilisi",
        "label": {
          "ka": "კომერციული ფართები იყიდება თბილისში",
          "en": "Commercial Property for sale in Tbilisi",
          "ru": "Продажа коммерческой недвижимости в Тбилиси"
        }
      },
      {
        "href": "/sale/land/tbilisi",
        "label": {
          "ka": "მიწის ნაკვეთები იყიდება თბილისში",
          "en": "Land Plots for sale in Tbilisi",
          "ru": "Продажа земельных участков в Тбилиси"
        }
      },
      {
        "href": "/sale/apartments/batumi",
        "label": {
          "ka": "ბინები იყიდება ბათუმში",
          "en": "Apartments for sale in Batumi",
          "ru": "Продажа квартир в Батуми"
        }
      },
      {
        "href": "/sale/apartments/kutaisi",
        "label": {
          "ka": "ბინები იყიდება ქუთაისში",
          "en": "Apartments for sale in Kutaisi",
          "ru": "Продажа квартир в Кутаиси"
        }
      },
      {
        "href": "/rent/apartments-3/tbilisi",
        "label": {
          "ka": "3-ოთახიანი ბინები ქირავდება თბილისში",
          "en": "3-Room Apartments for rent in Tbilisi",
          "ru": "Аренда 3-комнатных квартир в Тбилиси"
        }
      }
    ]
  },
  {
    "id": "cities",
    "title": {
      "ka": "ქალაქები",
      "en": "Cities",
      "ru": "Города"
    },
    "links": [
      {
        "href": "/tbilisi",
        "label": {
          "ka": "თბილისი",
          "en": "Tbilisi",
          "ru": "Тбилиси"
        }
      },
      {
        "href": "/batumi",
        "label": {
          "ka": "ბათუმი",
          "en": "Batumi",
          "ru": "Батуми"
        }
      },
      {
        "href": "/kutaisi",
        "label": {
          "ka": "ქუთაისი",
          "en": "Kutaisi",
          "ru": "Кутаиси"
        }
      },
      {
        "href": "/rustavi",
        "label": {
          "ka": "რუსთავი",
          "en": "Rustavi",
          "ru": "Рустави"
        }
      },
      {
        "href": "/poti",
        "label": {
          "ka": "ფოთი",
          "en": "Poti",
          "ru": "Поти"
        }
      },
      {
        "href": "/zugdidi",
        "label": {
          "ka": "ზუგდიდი",
          "en": "Zugdidi",
          "ru": "Зугдиди"
        }
      },
      {
        "href": "/telavi",
        "label": {
          "ka": "თელავი",
          "en": "Telavi",
          "ru": "Телави"
        }
      },
      {
        "href": "/gori",
        "label": {
          "ka": "გორი",
          "en": "Gori",
          "ru": "Гори"
        }
      },
      {
        "href": "/mtskheta",
        "label": {
          "ka": "მცხეთა",
          "en": "Mtskheta",
          "ru": "Мцхета"
        }
      },
      {
        "href": "/bakuriani",
        "label": {
          "ka": "ბაკურიანი",
          "en": "Bakuriani",
          "ru": "Бакуриани"
        }
      },
      {
        "href": "/kobuleti",
        "label": {
          "ka": "ქობულეთი",
          "en": "Kobuleti",
          "ru": "Кобулети"
        }
      },
      {
        "href": "/borjomi",
        "label": {
          "ka": "ბორჯომი",
          "en": "Borjomi",
          "ru": "Боржоми"
        }
      },
      {
        "href": "/gudauri",
        "label": {
          "ka": "გუდაური",
          "en": "Gudauri",
          "ru": "Гудаури"
        }
      },
      {
        "href": "/mestia",
        "label": {
          "ka": "მესტია",
          "en": "Mestia",
          "ru": "Местиа"
        }
      },
      {
        "href": "/sighnaghi",
        "label": {
          "ka": "სიღნაღი",
          "en": "Sighnaghi",
          "ru": "Сигнахи"
        }
      },
      {
        "href": "/tskaltubo",
        "label": {
          "ka": "წყალტუბო",
          "en": "Tskaltubo",
          "ru": "Цхалтубо"
        }
      },
      {
        "href": "/kazbegi",
        "label": {
          "ka": "ყაზბეგი",
          "en": "Kazbegi",
          "ru": "Казбеги"
        }
      },
      {
        "href": "/berlin",
        "label": {
          "ka": "ბერლინი",
          "en": "Berlin",
          "ru": "Берлин"
        }
      },
      {
        "href": "/hamburg",
        "label": {
          "ka": "ჰამბურგი",
          "en": "Hamburg",
          "ru": "Гамбург"
        }
      },
      {
        "href": "/munich",
        "label": {
          "ka": "მიუნხენი",
          "en": "Munich",
          "ru": "Мюнхен"
        }
      },
      {
        "href": "/cologne",
        "label": {
          "ka": "კელნი",
          "en": "Cologne",
          "ru": "Кёльн"
        }
      },
      {
        "href": "/frankfurt",
        "label": {
          "ka": "ფრანკფურტი",
          "en": "Frankfurt",
          "ru": "Франкфурт"
        }
      },
      {
        "href": "/stuttgart",
        "label": {
          "ka": "შტუტგარტი",
          "en": "Stuttgart",
          "ru": "Штутгарт"
        }
      },
      {
        "href": "/duesseldorf",
        "label": {
          "ka": "დიუსელდორფი",
          "en": "Düsseldorf",
          "ru": "Дюссельдорф"
        }
      },
      {
        "href": "/leipzig",
        "label": {
          "ka": "ლაიფციგი",
          "en": "Leipzig",
          "ru": "Лейпциг"
        }
      },
      {
        "href": "/dortmund",
        "label": {
          "ka": "დორტმუნდი",
          "en": "Dortmund",
          "ru": "Дортмунд"
        }
      },
      {
        "href": "/essen",
        "label": {
          "ka": "ესენი",
          "en": "Essen",
          "ru": "Эссен"
        }
      },
      {
        "href": "/bremen",
        "label": {
          "ka": "ბრემენი",
          "en": "Bremen",
          "ru": "Бремен"
        }
      },
      {
        "href": "/dresden",
        "label": {
          "ka": "დრეზდენი",
          "en": "Dresden",
          "ru": "Дрезден"
        }
      },
      {
        "href": "/hanover",
        "label": {
          "ka": "ჰანოვერი",
          "en": "Hanover",
          "ru": "Ганновер"
        }
      },
      {
        "href": "/nuremberg",
        "label": {
          "ka": "ნიურნბერგი",
          "en": "Nuremberg",
          "ru": "Нюрнберг"
        }
      },
      {
        "href": "/duisburg",
        "label": {
          "ka": "დუისბურგი",
          "en": "Duisburg",
          "ru": "Дуйсбург"
        }
      },
      {
        "href": "/bochum",
        "label": {
          "ka": "ბოხუმი",
          "en": "Bochum",
          "ru": "Бохум"
        }
      }
    ]
  }
]
