/**
 * Snapshot MAP_CITIES names (slug, ka, en) + aliases into a plain literal leaf.
 * ListingCard needs only the ka↔en label; importing user-place for it shipped
 * the whole world-places catalog (coords, metro, ~36 KB gz) to every card page.
 * place-label.check.ts fails on drift — rerun: npx tsx scripts/gen-city-names.ts
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { CITY_ALIASES, MAP_CITIES } from '../src/lib/map/user-place'

const rows = MAP_CITIES.map((c) => [c.slug, c.ka, c.en])
const out = `/* GENERATED by scripts/gen-city-names.ts — do not edit. Drift-locked by place-label.check.ts. */
export const CITY_NAMES: readonly (readonly [slug: string, ka: string, en: string])[] = ${JSON.stringify(rows)}

export const CITY_NAME_ALIASES: Readonly<Record<string, string>> = ${JSON.stringify(CITY_ALIASES)}
`
writeFileSync(fileURLToPath(new URL('../src/lib/city-names.gen.ts', import.meta.url)), out)
console.log(`city-names.gen.ts: ${rows.length} cities`)
