/**
 * Prebuild: snapshot footerKeywordCols() into a plain literal module.
 * The client Footer imports the snapshot, so the whole seo-pages → data/listings
 * graph (≈180 KB source) stays server-only. Regenerated on every prebuild, so it
 * can never drift from the live catalog + slug engine.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { footerKeywordCols } from '../src/lib/seo-pages'

const cols = footerKeywordCols()
const out = `/* GENERATED by scripts/gen-footer-cols.ts — do not edit; npm run prebuild refreshes.
 * Snapshot of seo-pages.footerKeywordCols() so the client Footer never imports the
 * seo-pages → data/listings graph. */
import type { FooterCol } from './seo-pages'

export const FOOTER_COLS: FooterCol[] = ${JSON.stringify(cols, null, 2)}
`
writeFileSync(fileURLToPath(new URL('../src/lib/footer-cols.gen.ts', import.meta.url)), out)
console.log(`footer-cols.gen.ts: ${cols.length} columns, ${cols.reduce((n, c) => n + c.links.length, 0)} links`)
