/**
 * run-real-photos-pipeline.ts
 *
 * Full multi-market real photos & renders pipeline:
 * Sweeps Berlin, Germany, UAE, Georgia, and Global projects.
 *
 * Usage:
 *   npx tsx scripts/run-real-photos-pipeline.ts --sweep-all
 *   npx tsx scripts/run-real-photos-pipeline.ts --region=ge
 *   npx tsx scripts/run-real-photos-pipeline.ts --region=uae
 *   npx tsx scripts/run-real-photos-pipeline.ts --region=de
 *   npx tsx scripts/run-real-photos-pipeline.ts --region=world
 */
import fs from 'node:fs'
import path from 'node:path'
import { PROJECTS, type Project } from '../src/data/professionals'
import { processProjectUniversal } from './fetch-real-project-photos'

const ROOT = path.resolve(__dirname, '..')
const MANIFEST_PATH = path.resolve(ROOT, '..', 'research', 'renders-manifest-2026-07.json')
const GALLERIES_PATH = path.resolve(ROOT, 'src', 'data', 'project-galleries.ts')

type ManifestEntry = {
  slug: string
  status: 'ok' | 'failed'
  source: string | null
  sourceUrl: string | null
  batch: number
  gallery?: string[]
}

async function loadManifest(): Promise<Map<string, ManifestEntry>> {
  if (!fs.existsSync(MANIFEST_PATH)) return new Map()
  try {
    const raw = fs.readFileSync(MANIFEST_PATH, 'utf8')
    const list: ManifestEntry[] = JSON.parse(raw)
    return new Map(list.map((e) => [e.slug, e]))
  } catch {
    return new Map()
  }
}

async function saveManifest(manifest: Map<string, ManifestEntry>) {
  const list = [...manifest.values()].sort((a, b) => a.slug.localeCompare(b.slug))
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(list, null, 2) + '\n')
}

async function emitGalleries(manifest: Map<string, ManifestEntry>) {
  const lines: string[] = []
  for (const [slug, entry] of [...manifest.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    if (entry.gallery && entry.gallery.length > 0) {
      lines.push(`  '${slug}': [${entry.gallery.map((g) => `'${g}'`).join(', ')}],`)
    }
  }
  const content = `// Generated by scripts/fetch-real-project-photos.ts & mirror-project-renders.ts
// Real photos and architectural renders mirrored from official & verified sources.
export const PROJECT_GALLERIES: Record<string, string[]> = {
${lines.join('\n')}
}
`
  fs.writeFileSync(GALLERIES_PATH, content)
  console.log(`Updated ${GALLERIES_PATH} with ${lines.length} galleries.`)
}

async function main() {
  const args = process.argv.slice(2)
  const regionArg = args.find((a) => a.startsWith('--region='))?.split('=')[1] || (args.includes('--sweep-all') ? 'all' : 'all')
  const limit = Number(args.find((a) => a.startsWith('--limit='))?.split('=')[1] || 9999)

  const manifest = await loadManifest()

  const geCities = new Set(['თბილისი', 'ბათუმი', 'ქუთაისი', 'რუსთავი', 'ბაკურიანი', 'გუდაური', 'გონიო', 'კვარიათი', 'ჩაქვი', 'ქობულეთი', 'სურამი', 'თელავი', 'სიღნაღი', 'ყვარელი', 'ბორჯომი', 'წყალტუბო', 'მცხეთა', 'ზუგდიდი', 'ფოთი', 'ურეკი', 'შეკვეთილი', 'გორი', 'Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi'])
  const uaeCities = new Set(['დუბაი', 'აბუ-დაბი', 'შარჯა', 'რას-ელ-ხაიმა', 'Dubai', 'Abu Dhabi', 'Sharjah', 'Ras Al Khaimah'])

  let targets: Project[] = []

  for (const p of PROJECTS) {
    let region = 'world'
    if (p.city === 'ბერლინი' || p.city === 'Berlin' || p.cc === 'DE' || ['Munich', 'Frankfurt', 'Hamburg', 'Cologne', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dresden', 'Nuremberg'].includes(p.city)) region = 'de'
    else if (p.cc === 'AE' || uaeCities.has(p.city)) region = 'uae'
    else if (geCities.has(p.city) || (!p.cc && (p.location?.includes('თბილის') || p.location?.includes('ბათუმ')))) region = 'ge'

    if (regionArg === 'all' || regionArg === region) {
      targets.push(p)
    }
  }

  targets = targets.slice(0, limit)
  console.log(`Starting universal real photo & render pipeline for ${targets.length} projects (region=${regionArg})...`)

  let updatedCount = 0
  let skipCount = 0
  let unhandledCount = 0

  for (let i = 0; i < targets.length; i++) {
    const p = targets[i]!
    const heroPath = path.join(ROOT, 'public', 'images', 'projects', `${p.slug}.webp`)
    const hasHero = fs.existsSync(heroPath) && fs.statSync(heroPath).size >= 16000
    const entry = manifest.get(p.slug)
    const hasGallery = entry?.gallery && entry.gallery.length > 0

    if (hasHero && hasGallery) {
      skipCount++
      continue
    }

    console.log(`[${i + 1}/${targets.length}] Searching online for "${p.name}" (${p.city}, ${p.slug})...`)
    const res = await processProjectUniversal(p, { forceHero: !hasHero, forceGallery: !hasGallery })

    if (res.hero || res.galleries.length > 0) {
      updatedCount++
      console.log(`  ✓ OK: ${p.slug} [${res.source}] → hero: ${res.hero}, galleries: +${res.galleries.length}`)
      manifest.set(p.slug, {
        slug: p.slug,
        status: 'ok',
        source: res.source || 'online',
        sourceUrl: null,
        batch: 5,
        gallery: [...new Set([...(entry?.gallery || []), ...res.galleries])],
      })
    } else {
      unhandledCount++
      console.log(`  ✗ No online images found for ${p.slug}`)
    }

    if (i % 15 === 0) {
      await saveManifest(manifest)
      await emitGalleries(manifest)
    }
  }

  await saveManifest(manifest)
  await emitGalleries(manifest)

  console.log(`\nUniversal pipeline completed: ${updatedCount} updated, ${skipCount} skipped (already complete), ${unhandledCount} unhandled.`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
